(() => {
  const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const dot = document.querySelector('.cursor-dot');
  let dx = innerWidth / 2, dy = innerHeight / 2, tx = dx, ty = dy;
  addEventListener('pointermove', e => { tx = e.clientX; ty = e.clientY; });
  function cursor(){ dx += (tx - dx) * .17; dy += (ty - dy) * .17; dot.style.left = dx + 'px'; dot.style.top = dy + 'px'; requestAnimationFrame(cursor); } cursor();
  document.querySelectorAll('.magnetic').forEach(el => { el.addEventListener('pointermove', e => { const r = el.getBoundingClientRect(); el.style.transform = `translate(${(e.clientX-r.left-r.width/2)*.17}px, ${(e.clientY-r.top-r.height/2)*.17}px)`; }); el.addEventListener('pointerleave', () => el.style.transform = ''); });
  document.querySelectorAll('.project').forEach(el => { el.addEventListener('pointermove', e => { const r = el.getBoundingClientRect(), x = (e.clientX-r.left)/r.width-.5, y = (e.clientY-r.top)/r.height-.5; el.style.transform = `perspective(900px) rotateX(${-y*5}deg) rotateY(${x*5}deg) translateY(-10px)`; }); el.addEventListener('pointerleave', () => el.style.transform = ''); });
  const sections = [...document.querySelectorAll('main section[id]')], navs = [...document.querySelectorAll('.nav nav a:not(.nav-mobile-cta)')];
  const navObserver = new IntersectionObserver(entries => entries.forEach(entry => { if(entry.isIntersecting) navs.forEach(link => link.classList.toggle('active', link.getAttribute('href') === '#' + entry.target.id)); }), { rootMargin:'-35% 0px -55% 0px' }); sections.forEach(s => navObserver.observe(s));
  const counterObserver = new IntersectionObserver(entries => entries.forEach(entry => { if(!entry.isIntersecting) return; entry.target.querySelectorAll('[data-count]').forEach(el => { const end = +el.dataset.count, suffix = el.dataset.suffix || '', start = performance.now(); const run = now => { const progress = Math.min((now-start)/1300,1); el.textContent = Math.round(end*(1-Math.pow(1-progress,3))) + suffix; if(progress<1) requestAnimationFrame(run); }; requestAnimationFrame(run); }); counterObserver.unobserve(entry.target); }), { threshold:.45 }); document.querySelectorAll('.signal-grid').forEach(el => counterObserver.observe(el));
  if(reduce) return;
  const canvas = document.querySelector('.particle-canvas'), ctx = canvas.getContext('2d'); let w,h,points=[];
  const resize = () => { ctx.setTransform(1,0,0,1,0,0); w=canvas.width=canvas.offsetWidth*devicePixelRatio; h=canvas.height=canvas.offsetHeight*devicePixelRatio; ctx.scale(devicePixelRatio,devicePixelRatio); const cw=canvas.offsetWidth,ch=canvas.offsetHeight; points=Array.from({length:Math.min(52,Math.floor(cw/25))},()=>({x:Math.random()*cw,y:Math.random()*ch,vx:(Math.random()-.5)*.24,vy:(Math.random()-.5)*.24})); }; resize(); addEventListener('resize',resize);
  function draw(){ const cw=canvas.offsetWidth,ch=canvas.offsetHeight; ctx.clearRect(0,0,cw,ch); points.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>cw)p.vx*=-1;if(p.y<0||p.y>ch)p.vy*=-1;}); ctx.strokeStyle='rgba(21,21,21,.16)'; for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<115){ctx.globalAlpha=1-d/115;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}ctx.globalAlpha=1;ctx.fillStyle='#ff6d44';points.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,1.5,0,7);ctx.fill();});requestAnimationFrame(draw);} draw();
})();
